theme: minima
title: jraizer blog
author: Josué Raizer
email: jraizer@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Aqui vou brincar com ciência de dados e programação.

# social links
cv-lattes_username: http://lattes.cnpq.br/4976414949967775 # DO NOT include the @ character, or else the build will fail!
github_username:  https://github.com/jraizer # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
